### ISSUE TITLE
On frontend, the absence of .env file causes error on initial docker-compose build

### ISSUE THREAD

**Issue by victorkane** [TannerGabriel/docker-node-mongodb#2]
I thoroughly enjoyed your tutorial https://gabrieltanner.org/blog/docker-compose, and the examples are great. However, along the same pedagogical lines, the error that pops out complaining that the frontend build cannot continue since the COPY of the `.env` file fails (doesn't exist) comes as a surprise. Of course, I understand that it's not good practice to put dotenv files in the repo. However, the inclusion of README instructions for the .env file in the non-docker, docker and docker-compose contexts would be great. Additionally, an `example.env` file might be included in the repo. Thanks again for sharing this highly instructive material!

Furthermore, the absence of the `.env` file means that no TODO's are written to the database. :)

**Comment by TannerGabriel** [comment]
Thank you for the information. I will look into it and fix it as soon as I can.

**Comment by augustosalazar** [comment]
Tanner, thanks for the great material, hoping for a fix for this issue. Thanks again

**Comment by TannerGabriel** [comment]
It should be fixed now. I had to use a workaround for getting the external IP-Adress into the Vue.js container, which you can see in the shell file I included.
